# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  Prem

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: UiPathInstallPlatform@6
  inputs:
    cliVersion: 'CustomVersion'
    cliNupkgPath: '"C:\agent\_work\_tool\uipcli\UiPath.CLI.Windows.24.10.3.2"'
- task: UiPathPack@5
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)'
    orchestratorConnection: 'Doc'
    outputPath: '$(Build.ArtifactStagingDirectory)\Output'
- task: UiPathDeploy@5
  inputs:
    orchestratorConnection: 'Doc'
    packagesPath: '$(Build.ArtifactStagingDirectory)\Output'
    folderName: 'Prem'
    traceLevel: 'Verbose'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'